services:
  backry:
    image: cefadrom/backry:latest
    restart: unless-stopped
    hostname: backry
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - db:/app/db

volumes:
  db:
