on:
    push:
        branches:
            - '*'
        paths:
            - 'src/**'

jobs:
    check:
        name: Svelte Check
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up Bun
                uses: oven-sh/setup-bun@v2

            -   name: Install dependencies
                run: bun install --frozen-lockfile

            -   name: Run Svelte check
                run: bun -c run check
